apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.22
        ports:
        - containerPort: 80
        env:
        - name: NGINX_HOST
          valueFrom:
            configMapKeyRef:
              key: NGINX_HOST
              name: nginx
        - name: NGINX_PORT
          valueFrom:
            configMapKeyRef:
              key: NGINX_PORT
              name: nginx
        volumeMounts:
          - mountPath: /var/www/html
            name: fe-pvc
      volumes:
        - name: fe-pvc
          persistentVolumeClaim:
            claimName: frontend-nginx